# Generated by Django 4.2.6 on 2023-11-29 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acessoperfil',
            fields=[
                ('idperfil', models.AutoField(db_column='IDPerfil', primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Descricao', max_length=50, null=True)),
                ('situacao', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Situacao', max_length=1, null=True)),
            ],
            options={
                'db_table': 'Acessoperfil',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Carimbo',
            fields=[
                ('idcarimbo', models.AutoField(db_column='IDCarimbo', primary_key=True, serialize=False)),
                ('descricao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Descricao', max_length=1000)),
                ('carimboerp', models.IntegerField(blank=True, db_column='CarimboERP', null=True)),
                ('situacao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Situacao', max_length=1)),
                ('desccomplementar', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DescComplementar', max_length=500, null=True)),
            ],
            options={
                'db_table': 'Carimbo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cascata',
            fields=[
                ('idcascata', models.AutoField(db_column='IDCascata', primary_key=True, serialize=False)),
                ('descascata', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DesCascata', max_length=40)),
                ('situacao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Situacao', max_length=1)),
            ],
            options={
                'db_table': 'Cascata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('codibge', models.IntegerField(db_column='CodIBGE', primary_key=True, serialize=False)),
                ('descidade', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DesCidade', max_length=100)),
                ('uf', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='UF', max_length=2)),
                ('ddd', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DDD', max_length=3, null=True)),
            ],
            options={
                'db_table': 'Cidade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.AutoField(db_column='IDCliente', primary_key=True, serialize=False)),
                ('coderp', models.IntegerField(db_column='CodERP')),
                ('cnpjcpf', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='CNPJCPF', max_length=18)),
                ('razao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Razao', max_length=250)),
                ('fantasia', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Fantasia', max_length=40)),
                ('cidade', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Cidade', max_length=100)),
                ('ufcliente', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='UFCliente', max_length=2)),
                ('situacao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Situacao', max_length=1)),
            ],
            options={
                'db_table': 'Cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClienteContato',
            fields=[
                ('idcontato', models.AutoField(db_column='IDContato', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Nome', max_length=60)),
                ('datanascimento', models.DateField(blank=True, db_column='DataNascimento', null=True)),
                ('funcao', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Funcao', max_length=30, null=True)),
                ('departamento', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Departamento', max_length=30, null=True)),
                ('telfixo', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TelFixo', max_length=15, null=True)),
                ('telcelular', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TelCelular', max_length=15, null=True)),
                ('numwhats', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='NumWhats', max_length=15, null=True)),
                ('emailcorp', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='EmailCorp', max_length=100, null=True)),
                ('pedidocorp', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='PedidoCorp', max_length=1)),
                ('emailpessoal', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='EmailPessoal', max_length=100, null=True)),
                ('pedidopessoal', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='PedidoPessoal', max_length=1)),
                ('situacao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Situacao', max_length=1)),
            ],
            options={
                'db_table': 'ClienteContato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClienteEndereco',
            fields=[
                ('idendereco', models.AutoField(db_column='IDEndereco', primary_key=True, serialize=False)),
                ('cep', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='CEP', max_length=8)),
                ('logradouro', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Logradouro', max_length=60)),
                ('numero', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Numero', max_length=10, null=True)),
                ('complemento', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Complemento', max_length=60, null=True)),
                ('bairro', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Bairro', max_length=50)),
                ('tipoendereco', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TipoEndereco', max_length=1)),
                ('situacao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Situacao', max_length=1)),
            ],
            options={
                'db_table': 'ClienteEndereco',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClienteTipo',
            fields=[
                ('idclientetipo', models.AutoField(db_column='IDClienteTipo', primary_key=True, serialize=False)),
                ('descricao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Descricao', max_length=200)),
                ('clientetipoerp', models.IntegerField(blank=True, db_column='ClienteTipoERP', null=True)),
                ('situacao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Situacao', max_length=1)),
            ],
            options={
                'db_table': 'ClienteTipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClienteVendedor',
            fields=[
                ('idclientevendedor', models.AutoField(db_column='IDClienteVendedor', primary_key=True, serialize=False)),
                ('idusuario', models.IntegerField(db_column='IDUsuario')),
                ('tipousuario', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TipoUsuario', max_length=1)),
            ],
            options={
                'db_table': 'ClienteVendedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equipevenda',
            fields=[
                ('idequipe', models.AutoField(db_column='IDEquipe', primary_key=True, serialize=False)),
                ('desequipe', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DesEquipe', max_length=40)),
                ('nivel1', models.IntegerField(db_column='Nivel1')),
                ('nivel2', models.IntegerField(blank=True, db_column='Nivel2', null=True)),
                ('nivel3', models.IntegerField(blank=True, db_column='Nivel3', null=True)),
                ('situacao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Situacao', max_length=1)),
            ],
            options={
                'db_table': 'Equipevenda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fretecif',
            fields=[
                ('idfretecif', models.AutoField(db_column='IDFreteCIF', primary_key=True, serialize=False)),
                ('desfretecif', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DesFreteCIF', max_length=40)),
                ('perdesconto1', models.DecimalField(db_column='PerDesconto1', decimal_places=2, max_digits=4)),
                ('perdesconto2', models.DecimalField(db_column='PerDesconto2', decimal_places=2, max_digits=4)),
                ('datainicial', models.DateField(db_column='DataInicial')),
                ('datafinal', models.DateField(db_column='DataFinal')),
                ('situacao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Situacao', max_length=1)),
            ],
            options={
                'db_table': 'Fretecif',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GrupoEconomico',
            fields=[
                ('idgrupoeconomico', models.AutoField(db_column='IDGrupoEconomico', primary_key=True, serialize=False)),
                ('descricao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Descricao', max_length=200)),
                ('grupoeconomicoerp', models.IntegerField(blank=True, db_column='GrupoEconomicoERP', null=True)),
                ('situacao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Situacao', max_length=1)),
            ],
            options={
                'db_table': 'GrupoEconomico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Linhaproduto',
            fields=[
                ('idlinha', models.AutoField(db_column='IDLinha', primary_key=True, serialize=False)),
                ('deslinha', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DesLinha', max_length=40)),
                ('estrutura', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Estrutura', max_length=1)),
                ('situacao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Situacao', max_length=1)),
            ],
            options={
                'db_table': 'Linhaproduto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('idmenu', models.AutoField(db_column='IDMenu', primary_key=True, serialize=False)),
                ('descmenu', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DescMenu', max_length=50)),
                ('nivel', models.IntegerField(db_column='Nivel')),
                ('ordem', models.IntegerField(db_column='Ordem')),
                ('icone', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Icone', max_length=200, null=True)),
                ('url_redirect', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Url_Redirect', max_length=500, null=True)),
            ],
            options={
                'db_table': 'Menu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Organograma',
            fields=[
                ('idorganograma', models.AutoField(db_column='IDOrganograma', primary_key=True, serialize=False)),
                ('descricao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Descricao', max_length=50)),
                ('nivel', models.IntegerField(db_column='Nivel')),
            ],
            options={
                'db_table': 'Organograma',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Politicacomissao',
            fields=[
                ('idpolcomissao', models.AutoField(db_column='IDPolComissao', primary_key=True, serialize=False)),
                ('despolitica', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DesPolitica', max_length=40)),
                ('percomissao', models.DecimalField(db_column='PerComissao', decimal_places=2, max_digits=4)),
                ('percomnovos', models.DecimalField(db_column='PerComNovos', decimal_places=2, max_digits=4)),
                ('situacao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Situacao', max_length=1)),
            ],
            options={
                'db_table': 'Politicacomissao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrecoRegra',
            fields=[
                ('idprecoregra', models.AutoField(db_column='IDPrecoRegra', primary_key=True, serialize=False)),
                ('desregra', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DesRegra', max_length=40)),
                ('datainicial', models.DateField(db_column='DataInicial')),
                ('datafinal', models.DateField(db_column='DataFinal')),
                ('peracrescimo', models.DecimalField(db_column='PerAcrescimo', decimal_places=2, max_digits=5)),
                ('perdesconto', models.DecimalField(db_column='PerDesconto', decimal_places=2, max_digits=4)),
                ('ipi', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='IPI', max_length=1)),
                ('st', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ST', max_length=1)),
                ('pis', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='PIS', max_length=1)),
                ('cofins', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='COFINS', max_length=1)),
                ('icms', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ICMS', max_length=1)),
            ],
            options={
                'db_table': 'PrecoRegra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rede',
            fields=[
                ('idrede', models.AutoField(db_column='IDRede', primary_key=True, serialize=False)),
                ('descricao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Descricao', max_length=200)),
                ('redeerp', models.IntegerField(blank=True, db_column='RedeERP', null=True)),
                ('situacao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Situacao', max_length=1)),
            ],
            options={
                'db_table': 'Rede',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegiaoVenda',
            fields=[
                ('idregiao', models.AutoField(db_column='IDRegiao', primary_key=True, serialize=False)),
                ('desregiao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DesRegiao', max_length=100)),
                ('situacao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Situacao', max_length=1)),
                ('coderp', models.IntegerField(blank=True, db_column='CodERP', null=True)),
            ],
            options={
                'db_table': 'RegiaoVenda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Representada',
            fields=[
                ('idrepresentada', models.AutoField(db_column='IDRepresentada', primary_key=True, serialize=False)),
                ('cnpj', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='CNPJ', max_length=18)),
                ('razao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Razao', max_length=250)),
                ('fantasia', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Fantasia', max_length=40)),
                ('cep', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='CEP', max_length=8)),
                ('numero', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Numero', max_length=10, null=True)),
                ('complemento', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Complemento', max_length=60, null=True)),
                ('bairro', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Bairro', max_length=50)),
                ('datafundacao', models.DateField(blank=True, db_column='DataFundacao', null=True)),
                ('inscestadual', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='InscEstadual', max_length=20, null=True)),
                ('inscmunicipal', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='InscMunicipal', max_length=20, null=True)),
                ('telfixo', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TelFixo', max_length=15, null=True)),
                ('telcelular', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TelCelular', max_length=15, null=True)),
                ('whatsapp', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Whatsapp', max_length=15, null=True)),
                ('email', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Email', max_length=100, null=True)),
                ('coderp', models.IntegerField(db_column='CodERP')),
                ('situacao', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Situacao', max_length=1, null=True)),
                ('logradouro', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Logradouro', max_length=200)),
            ],
            options={
                'db_table': 'Representada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TabGeral',
            fields=[
                ('idtabgeral', models.AutoField(db_column='IDTabGeral', primary_key=True, serialize=False)),
                ('identificador', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Identificador', max_length=20)),
                ('codidentificador', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='CodIdentificador', max_length=10)),
                ('descricao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Descricao', max_length=255)),
                ('texto', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Texto', max_length=250, null=True)),
                ('situacao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Situacao', max_length=1)),
            ],
            options={
                'db_table': 'TabGeral',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoFrete',
            fields=[
                ('idtipofrete', models.AutoField(db_column='IDTipoFrete', primary_key=True, serialize=False)),
                ('descricao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Descricao', max_length=1000)),
                ('tipofreteerp', models.IntegerField(blank=True, db_column='TipoFreteERP', null=True)),
                ('situacao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Situacao', max_length=1)),
            ],
            options={
                'db_table': 'TipoFrete',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPedido',
            fields=[
                ('idtipopedido', models.AutoField(db_column='IDTipoPedido', primary_key=True, serialize=False)),
                ('destipopedido', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DesTipoPedido', max_length=40)),
                ('temvolume', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TemVolume', max_length=1)),
                ('temcascata', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TemCascata', max_length=1)),
                ('temmargem', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TemMargem', max_length=1)),
                ('temminimo', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TemMinimo', max_length=1)),
                ('temestoque', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TemEstoque', max_length=1)),
                ('coderp', models.IntegerField(db_column='CodERP')),
                ('idpreco', models.IntegerField(blank=True, db_column='IDPreco', null=True)),
                ('idmargem', models.IntegerField(blank=True, db_column='IDMargem', null=True)),
                ('situacao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Situacao', max_length=1)),
                ('ordemimpressao', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='OrdemImpressao', max_length=1, null=True)),
                ('layoutimpressao', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='LayoutImpressao', max_length=1, null=True)),
                ('alterarvalorfrete', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='AlterarValorFrete', max_length=1)),
            ],
            options={
                'db_table': 'TipoPedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipousuario',
            fields=[
                ('idtipousuario', models.IntegerField(db_column='IDTipoUsuario', primary_key=True, serialize=False)),
                ('descricao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Descricao', max_length=30)),
                ('situacao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Situacao', max_length=1)),
                ('tipo', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Tipo', max_length=3)),
            ],
            options={
                'db_table': 'Tipousuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transportador',
            fields=[
                ('idtransportador', models.AutoField(db_column='IDTransportador', primary_key=True, serialize=False)),
                ('coderp', models.IntegerField(db_column='CodERP')),
                ('cnpjcpf', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='CNPJCPF', max_length=20, unique=True)),
                ('razao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Razao', max_length=150)),
                ('fantasia', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Fantasia', max_length=150)),
                ('situacao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Situacao', max_length=1)),
                ('telfixo', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TelFixo', max_length=15, null=True)),
                ('telcelular', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TelCelular', max_length=15, null=True)),
                ('email', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Email', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Transportador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(db_column='IDUsuario', primary_key=True, serialize=False)),
                ('email', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Email', max_length=100)),
                ('nome', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Nome', max_length=30)),
                ('sobrenome', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Sobrenome', max_length=20)),
                ('telcelular', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TelCelular', max_length=15)),
                ('situacao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Situacao', max_length=1)),
                ('idlocal', models.IntegerField(db_column='IDLocal')),
                ('datacadastro', models.DateTimeField(db_column='DataCadastro')),
                ('dataatualiza', models.DateTimeField(db_column='DataAtualiza')),
                ('senha', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Senha', max_length=32, null=True)),
                ('foto', models.BinaryField(blank=True, db_column='Foto', max_length='max', null=True)),
                ('cpfcnpj', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='CPFCNPJ', max_length=18, null=True)),
                ('usuarioerp', models.IntegerField(blank=True, db_column='UsuarioERP', null=True)),
                ('coderp', models.IntegerField(blank=True, db_column='CodERP', null=True)),
                ('usarbackoffice', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='UsarBackOffice', max_length=1)),
                ('usarorcamento', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='UsarOrcamento', max_length=1)),
            ],
            options={
                'db_table': 'Usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('idvolume', models.AutoField(db_column='IDVolume', primary_key=True, serialize=False)),
                ('desvolume', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DesVolume', max_length=40)),
                ('datainicial', models.DateField(db_column='DataInicial')),
                ('datafinal', models.DateField(db_column='DataFinal')),
                ('situacao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Situacao', max_length=1)),
            ],
            options={
                'db_table': 'Volume',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClienteB2B',
            fields=[
                ('idusuario', models.OneToOneField(db_column='IDUsuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='backoffice.usuario')),
                ('cnpjcliente', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='CNPJCliente', max_length=18)),
                ('codvendedor', models.IntegerField(db_column='CodVendedor')),
                ('perdesconto', models.DecimalField(blank=True, db_column='PerDesconto', decimal_places=2, max_digits=4, null=True)),
                ('percomissao', models.DecimalField(blank=True, db_column='PerComissao', decimal_places=2, max_digits=4, null=True)),
            ],
            options={
                'db_table': 'ClienteB2B',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClienteDado',
            fields=[
                ('idcliente', models.OneToOneField(db_column='IDCliente', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='backoffice.cliente')),
                ('cep', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='CEP', max_length=8)),
                ('logradouro', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Logradouro', max_length=60)),
                ('numero', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Numero', max_length=15, null=True)),
                ('complemento', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Complemento', max_length=60, null=True)),
                ('bairro', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Bairro', max_length=50)),
                ('datafundacao', models.DateField(blank=True, db_column='DataFundacao', null=True)),
                ('telfixo', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TelFixo', max_length=15, null=True)),
                ('telcelular', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TelCelular', max_length=15, null=True)),
                ('email', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Email', max_length=100, null=True)),
            ],
            options={
                'db_table': 'ClienteDado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClienteEspecial',
            fields=[
                ('idcliente', models.OneToOneField(db_column='IDCliente', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='backoffice.cliente')),
                ('regsuframa', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='RegSuframa', max_length=20, null=True)),
                ('dataregsuframa', models.DateField(blank=True, db_column='DataRegSuframa', null=True)),
                ('datavalsuframa', models.DateField(blank=True, db_column='DataValSuframa', null=True)),
                ('regtare', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='RegTare', max_length=20, null=True)),
                ('dataregtare', models.DateField(blank=True, db_column='DataRegTare', null=True)),
                ('datavaltare', models.DateField(blank=True, db_column='DataValTare', null=True)),
                ('descricaocarimbo', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DescricaoCarimbo', max_length=500, null=True)),
            ],
            options={
                'db_table': 'ClienteEspecial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClienteFiscal',
            fields=[
                ('idcliente', models.OneToOneField(db_column='IDCliente', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='backoffice.cliente')),
                ('cnaeprincipal', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='CNAEPrincipal', max_length=7, null=True)),
                ('inscestadual', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='InscEstadual', max_length=20, null=True)),
                ('inscmunicipal', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='InscMunicipal', max_length=20, null=True)),
                ('contribuinteicms', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ContribuinteICMS', max_length=1)),
                ('orgaopublico', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='OrgaoPublico', max_length=1)),
            ],
            options={
                'db_table': 'ClienteFiscal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientePerfil',
            fields=[
                ('idcliente', models.OneToOneField(db_column='IDCliente', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='backoffice.cliente')),
                ('descomposto', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DesComposto', max_length=20, null=True)),
                ('perdesconto', models.DecimalField(blank=True, db_column='PerDesconto', decimal_places=2, max_digits=4, null=True)),
                ('pedidominimo', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='PedidoMinimo', max_length=1, null=True)),
                ('limitecredito', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='LimiteCredito', max_length=1, null=True)),
                ('idtransportador', models.IntegerField(blank=True, db_column='IDTransportador', null=True)),
                ('descgeral', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DescGeral', max_length=500, null=True)),
                ('presencacomprador', models.IntegerField(blank=True, db_column='PresencaComprador', null=True)),
                ('prazomedio', models.IntegerField(blank=True, db_column='PrazoMedio', null=True)),
            ],
            options={
                'db_table': 'ClientePerfil',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClienteVisita',
            fields=[
                ('idclientevendedor', models.OneToOneField(db_column='IDClienteVendedor', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='backoffice.clientevendedor')),
                ('seg', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Seg', max_length=1)),
                ('ter', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Ter', max_length=1)),
                ('qua', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Qua', max_length=1)),
                ('qui', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Qui', max_length=1)),
                ('sex', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Sex', max_length=1)),
                ('sab', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Sab', max_length=1)),
                ('dom', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Dom', max_length=1)),
                ('hora1', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Hora1', max_length=5, null=True)),
                ('hora2', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Hora2', max_length=5, null=True)),
                ('recorrencia', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Recorrencia', max_length=12, null=True)),
            ],
            options={
                'db_table': 'ClienteVisita',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MenuFavorito',
            fields=[
                ('idfavorito', models.AutoField(db_column='IDFavorito', primary_key=True, serialize=False)),
                ('idmenu', models.ForeignKey(blank=True, db_column='IDMenu', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backoffice.menu')),
                ('idusuario', models.ForeignKey(blank=True, db_column='IDUsuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backoffice.usuario')),
            ],
            options={
                'db_table': 'MenuFavorito',
            },
        ),
    ]
