# Generated by Django 4.2.6 on 2023-12-21 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idcategoria', models.AutoField(db_column='IDCategoria', primary_key=True, serialize=False)),
                ('descricao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Descricao', max_length=200)),
                ('categoriaerp', models.IntegerField(blank=True, db_column='CategoriaERP', null=True)),
                ('situacao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Situacao', max_length=1)),
            ],
            options={
                'db_table': 'Categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComDesconto',
            fields=[
                ('idcomdesconto', models.AutoField(db_column='IDComDesconto', primary_key=True, serialize=False)),
                ('descomissaodesc', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DesComissaoDesc', max_length=40)),
            ],
            options={
                'db_table': 'ComDesconto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('idfamilia', models.AutoField(db_column='IDFamilia', primary_key=True, serialize=False)),
                ('descricao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Descricao', max_length=200)),
                ('familiaerp', models.IntegerField(blank=True, db_column='FamiliaERP', null=True)),
                ('situacao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Situacao', max_length=1)),
            ],
            options={
                'db_table': 'Familia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GrandeGrupo',
            fields=[
                ('idgrandegrupo', models.AutoField(db_column='IDGrandeGrupo', primary_key=True, serialize=False)),
                ('descricao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Descricao', max_length=200)),
                ('grandegrupoerp', models.IntegerField(blank=True, db_column='GrandeGrupoERP', null=True)),
                ('situacao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Situacao', max_length=1)),
            ],
            options={
                'db_table': 'GrandeGrupo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('idgrupo', models.AutoField(db_column='IDGrupo', primary_key=True, serialize=False)),
                ('descricao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Descricao', max_length=200)),
                ('grupoerp', models.IntegerField(blank=True, db_column='GrupoERP', null=True)),
                ('situacao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Situacao', max_length=1)),
            ],
            options={
                'db_table': 'Grupo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LocalConfig',
            fields=[
                ('idlocal', models.IntegerField(db_column='IDLocal', primary_key=True, serialize=False)),
                ('comissao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Comissao', max_length=1)),
                ('desccooperado', models.DecimalField(db_column='DescCooperado', decimal_places=2, max_digits=4)),
                ('desclocal', models.DecimalField(db_column='DescLocal', decimal_places=2, max_digits=4)),
                ('deslimite', models.DecimalField(db_column='DesLimite', decimal_places=2, max_digits=4)),
                ('tipopedido', models.IntegerField(blank=True, db_column='TipoPedido', null=True)),
                ('prazomedio', models.IntegerField(db_column='PrazoMedio')),
                ('precoestrutura', models.IntegerField(blank=True, db_column='PrecoEstrutura', null=True)),
                ('comdesconto', models.IntegerField(blank=True, db_column='ComDesconto', null=True)),
                ('preco', models.IntegerField(db_column='Preco')),
                ('coddeperp', models.IntegerField(blank=True, db_column='CodDepERP', null=True)),
                ('repetiritem', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='RepetirItem', max_length=1)),
                ('liberardescontovolume', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='LiberarDescontoVolume', max_length=1)),
                ('habilitardescontocliente', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='HabilitarDescontoCliente', max_length=1)),
                ('habilitareventosdesconto', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='HabilitarEventosDesconto', max_length=1)),
                ('permitirvendabloqueado', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='PermitirVendaBloqueado', max_length=1)),
                ('visualizarsaldoestoque', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='VisualizarSaldoEstoque', max_length=1)),
                ('habilitardescontoadicional', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='HabilitarDescontoAdicional', max_length=1)),
                ('habilitarmargemvalor', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='HabilitarMargemValor', max_length=1)),
                ('mostrabanner', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='MostraBanner', max_length=1)),
                ('comissaocompartilhada', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ComissaoCompartilhada', max_length=1)),
                ('usarvalorcomimposto', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='UsarValorComImposto', max_length=1)),
                ('diasvalidade', models.IntegerField(blank=True, db_column='DiasValidade', null=True)),
                ('listarvendedor', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ListarVendedor', max_length=1)),
            ],
            options={
                'db_table': 'LocalConfig',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LocalVenda',
            fields=[
                ('idlocalvenda', models.AutoField(db_column='IDLocalVenda', primary_key=True, serialize=False)),
                ('cnpj', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='CNPJ', max_length=18)),
                ('razao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Razao', max_length=250)),
                ('fantasia', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Fantasia', max_length=40)),
                ('cep', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='CEP', max_length=8)),
                ('logradouro', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Logradouro', max_length=60)),
                ('numero', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Numero', max_length=10, null=True)),
                ('complemento', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Complemento', max_length=60, null=True)),
                ('bairro', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Bairro', max_length=50)),
                ('coderp', models.IntegerField(db_column='CodERP', unique=True)),
                ('situacao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Situacao', max_length=1)),
                ('foto', models.BinaryField(blank=True, db_column='Foto', max_length='max', null=True)),
            ],
            options={
                'db_table': 'LocalVenda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Margem',
            fields=[
                ('idmargem', models.AutoField(db_column='IDMargem', primary_key=True, serialize=False)),
                ('desmargem', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DesMargem', max_length=40)),
                ('perminproduto', models.DecimalField(blank=True, db_column='PerMinProduto', decimal_places=2, max_digits=5, null=True)),
                ('perminpedido', models.DecimalField(blank=True, db_column='PerMinPedido', decimal_places=2, max_digits=5, null=True)),
                ('perdesproduto', models.DecimalField(blank=True, db_column='PerDesProduto', decimal_places=2, max_digits=5, null=True)),
                ('perdespedido', models.DecimalField(blank=True, db_column='PerDesPedido', decimal_places=2, max_digits=5, null=True)),
                ('cor1', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Cor1', max_length=8)),
                ('cor2', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Cor2', max_length=8)),
                ('cor3', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Cor3', max_length=8)),
                ('situacao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Situacao', max_length=1)),
                ('visivel', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Visivel', max_length=1)),
                ('valor', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Valor', max_length=1)),
            ],
            options={
                'db_table': 'Margem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Preco',
            fields=[
                ('idpreco', models.AutoField(db_column='IDPreco', primary_key=True, serialize=False)),
                ('codtabela', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='CodTabela', max_length=15)),
                ('destabela', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DesTabela', max_length=150, null=True)),
                ('embtabela', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='EmbTabela', max_length=1)),
                ('permargdesejavel', models.DecimalField(db_column='PerMargDesejavel', decimal_places=2, max_digits=5)),
                ('permargminima', models.DecimalField(db_column='PerMargMinima', decimal_places=2, max_digits=5)),
                ('perdesconto', models.DecimalField(blank=True, db_column='PerDesconto', decimal_places=2, max_digits=4, null=True)),
                ('datainicial', models.DateField(db_column='DataInicial')),
                ('datafinal', models.DateField(db_column='DataFinal')),
                ('empresaerp', models.IntegerField(blank=True, db_column='EmpresaERP', null=True)),
                ('dtatualizacao', models.DateField(blank=True, db_column='DtAtualizacao', null=True)),
            ],
            options={
                'db_table': 'Preco',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrecoEstrutura',
            fields=[
                ('idprecoestrutura', models.AutoField(db_column='IDPrecoEstrutura', primary_key=True, serialize=False)),
                ('descprecoestrutura', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DescPrecoEstrutura', max_length=40)),
                ('datainicial', models.DateField(db_column='DataInicial')),
                ('datafinal', models.DateField(db_column='DataFinal')),
            ],
            options={
                'db_table': 'PrecoEstrutura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('idproduto', models.AutoField(db_column='IDProduto', primary_key=True, serialize=False)),
                ('sku', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='SKU', max_length=60, unique=True)),
                ('coderp', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='CodERP', max_length=60, unique=True)),
                ('deserp', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DesERP', max_length=250)),
                ('unimedida', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='UniMedida', max_length=6)),
                ('dessecundaria', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DesSecundaria', max_length=250, null=True)),
                ('codsecundario', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='CodSecundario', max_length=20, null=True)),
                ('fabricante', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Fabricante', max_length=40, null=True)),
                ('marca', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Marca', max_length=40, null=True)),
                ('situacao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Situacao', max_length=1)),
            ],
            options={
                'db_table': 'Produto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProdutoMensagem',
            fields=[
                ('idproduto', models.IntegerField(db_column='IDProduto', primary_key=True, serialize=False)),
                ('idlocal', models.IntegerField(db_column='IDLocal')),
                ('mensagem1', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Mensagem1', max_length=500, null=True)),
                ('mensagem2', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Mensagem2', max_length=500, null=True)),
                ('mensagem3', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Mensagem3', max_length=500, null=True)),
            ],
            options={
                'db_table': 'ProdutoMensagem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RepresDoc',
            fields=[
                ('iddoc', models.AutoField(db_column='IDDoc', primary_key=True, serialize=False)),
                ('datainclusao', models.DateField(db_column='DataInclusao')),
                ('documento', models.TextField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Documento')),
                ('datarevisao', models.DateField(blank=True, db_column='DataRevisao', null=True)),
            ],
            options={
                'db_table': 'RepresDoc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RepresentadaDoc',
            fields=[
                ('idrepresentada', models.OneToOneField(db_column='IDRepresentada', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='backoffice.representada')),
                ('iddocumento', models.IntegerField(db_column='IDDocumento')),
                ('dtinclusao', models.DateField(db_column='DtInclusao')),
                ('documento', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Documento', max_length=200)),
                ('dtrevisao', models.DateField(blank=True, db_column='DtRevisao', null=True)),
            ],
            options={
                'db_table': 'RepresentadaDoc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RepresentadaLocal',
            fields=[
                ('idrepresentada', models.OneToOneField(db_column='IDRepresentada', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='backoffice.representada')),
                ('localpadrao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='LocalPadrao', max_length=1)),
            ],
            options={
                'db_table': 'RepresentadaLocal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RepresentadaRegiao',
            fields=[
                ('idrepresentada', models.OneToOneField(db_column='IDRepresentada', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='backoffice.representada')),
            ],
            options={
                'db_table': 'RepresentadaRegiao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('idusuario', models.OneToOneField(db_column='IDUsuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='backoffice.usuario')),
                ('pedidos', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Pedidos', max_length=1)),
                ('preco', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Preco', max_length=1)),
            ],
            options={
                'db_table': 'Representante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubGrupo',
            fields=[
                ('idsubgrupo', models.AutoField(db_column='IDSubGrupo', primary_key=True, serialize=False)),
                ('descricao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Descricao', max_length=200)),
                ('subgrupoerp', models.IntegerField(blank=True, db_column='SubGrupoERP', null=True)),
                ('situacao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Situacao', max_length=1)),
            ],
            options={
                'db_table': 'SubGrupo',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='fretecif',
            table='FreteCIF',
        ),
        migrations.CreateModel(
            name='LocalEmail',
            fields=[
                ('idlocal', models.OneToOneField(db_column='IDLocal', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='backoffice.localvenda')),
                ('emailresposta', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='EmailResposta', max_length=150)),
                ('assunto', models.TextField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Assunto')),
                ('corpo', models.TextField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Corpo')),
                ('assinatura', models.TextField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Assinatura')),
            ],
            options={
                'db_table': 'LocalEmail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProdutoDados',
            fields=[
                ('idproduto', models.OneToOneField(db_column='IDProduto', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='backoffice.produto')),
                ('desresumida', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DesResumida', max_length=40, null=True)),
                ('ncm', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='NCM', max_length=20, null=True)),
                ('curvaabc', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='CurvaABC', max_length=2, null=True)),
                ('percomissao', models.DecimalField(blank=True, db_column='PerComissao', decimal_places=4, max_digits=7, null=True)),
                ('perdescmaximo', models.DecimalField(blank=True, db_column='PerDescMaximo', decimal_places=3, max_digits=6, null=True)),
            ],
            options={
                'db_table': 'ProdutoDados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProdutoInformacao',
            fields=[
                ('idproduto', models.OneToOneField(db_column='IDProduto', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='backoffice.produto')),
                ('desaplicacao', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DesAplicacao', null=True)),
                ('destecnica', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DesTecnica', null=True)),
                ('mensagem1', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Mensagem1', max_length=200, null=True)),
                ('mensagem2', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Mensagem2', max_length=200, null=True)),
                ('mensagem3', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Mensagem3', max_length=200, null=True)),
            ],
            options={
                'db_table': 'ProdutoInformacao',
                'managed': False,
            },
        ),
    ]
