# Generated by Django 4.2.6 on 2024-03-19 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_categoria_comdesconto_familia_grandegrupo_grupo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CascataFaixa',
            fields=[
                ('idcascatafaixa', models.AutoField(db_column='IDCascataFaixa', primary_key=True, serialize=False)),
                ('sigla', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Sigla', max_length=6)),
                ('permaximo', models.DecimalField(db_column='PerMaximo', decimal_places=2, max_digits=4)),
                ('tipocascata', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TipoCascata', max_length=1)),
            ],
            options={
                'db_table': 'CascataFaixa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComFaixa',
            fields=[
                ('idcomfaixa', models.AutoField(db_column='IDComFaixa', primary_key=True, serialize=False)),
                ('perdesconto', models.DecimalField(db_column='PerDesconto', decimal_places=2, max_digits=4)),
                ('fatorcom', models.DecimalField(db_column='FatorCom', decimal_places=4, max_digits=19)),
            ],
            options={
                'db_table': 'ComFaixa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DashGrafico',
            fields=[
                ('iddashgrafico', models.AutoField(db_column='IDDashGrafico', primary_key=True, serialize=False)),
                ('descricao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Descricao', max_length=150)),
                ('titulo', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Titulo', max_length=50)),
                ('iddashgrafico_grupo', models.IntegerField(blank=True, db_column='IDDashGrafico_Grupo', null=True)),
                ('situacao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Situacao', max_length=1)),
            ],
            options={
                'db_table': 'DashGrafico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DashGraficoDados',
            fields=[
                ('iddashgraficodados', models.AutoField(db_column='IDDashGraficoDados', primary_key=True, serialize=False)),
                ('ordemlinha', models.IntegerField(db_column='OrdemLinha')),
                ('ordemcoluna', models.IntegerField(db_column='OrdemColuna')),
                ('linha', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Linha', max_length=50)),
                ('coluna', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Coluna', max_length=25, null=True)),
                ('vlgrafico', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='VlGrafico', max_length=25)),
                ('grafico', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Grafico', max_length=1)),
            ],
            options={
                'db_table': 'DashGraficoDados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DashTipoGrafico',
            fields=[
                ('iddashtipografico', models.AutoField(db_column='IDDashTipoGrafico', primary_key=True, serialize=False)),
                ('descricao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Descricao', max_length=150)),
            ],
            options={
                'db_table': 'DashTipoGrafico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DescontoTipo',
            fields=[
                ('iddescontotipo', models.AutoField(db_column='IDDescontoTipo', primary_key=True, serialize=False)),
                ('dtinicial', models.DateField(db_column='DtInicial')),
                ('dtfinal', models.DateField(db_column='DtFinal')),
            ],
            options={
                'db_table': 'DescontoTipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DescontoTipoEstrutura',
            fields=[
                ('iddescontotipoestrutura', models.AutoField(db_column='IDDescontoTipoEstrutura', primary_key=True, serialize=False)),
                ('desconto', models.DecimalField(db_column='Desconto', decimal_places=3, max_digits=7)),
            ],
            options={
                'db_table': 'DescontoTipoEstrutura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmbUnidade',
            fields=[
                ('idproduto', models.OneToOneField(db_column='IDProduto', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='backoffice.produto')),
                ('unidade', models.IntegerField(db_column='Unidade')),
                ('pesobruto', models.DecimalField(blank=True, db_column='PesoBruto', decimal_places=4, max_digits=10, null=True)),
                ('pesoliquido', models.DecimalField(blank=True, db_column='PesoLiquido', decimal_places=4, max_digits=10, null=True)),
                ('largura', models.DecimalField(blank=True, db_column='Largura', decimal_places=4, max_digits=10, null=True)),
                ('altura', models.DecimalField(blank=True, db_column='Altura', decimal_places=4, max_digits=10, null=True)),
                ('comprimento', models.DecimalField(blank=True, db_column='Comprimento', decimal_places=4, max_digits=10, null=True)),
                ('m3', models.DecimalField(blank=True, db_column='M3', decimal_places=4, max_digits=10, null=True)),
                ('codgtin', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='CodGTIN', max_length=20, null=True)),
                ('fcvenda', models.DecimalField(blank=True, db_column='FCVenda', decimal_places=4, max_digits=10, null=True)),
                ('unimedida', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='UniMedida', max_length=12, null=True)),
                ('minvenda', models.DecimalField(blank=True, db_column='MinVenda', decimal_places=4, max_digits=19, null=True)),
                ('multvenda', models.DecimalField(blank=True, db_column='MultVenda', decimal_places=4, max_digits=19, null=True)),
                ('qtcaixa', models.DecimalField(blank=True, db_column='QTCaixa', decimal_places=4, max_digits=19, null=True)),
            ],
            options={
                'db_table': 'EmbUnidade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('idempresa', models.AutoField(db_column='IDEmpresa', primary_key=True, serialize=False)),
                ('cnpj', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='CNPJ', max_length=18)),
                ('razao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Razao', max_length=250)),
                ('fantasia', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Fantasia', max_length=40)),
                ('cep', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='CEP', max_length=8)),
                ('numero', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Numero', max_length=10, null=True)),
                ('complemento', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Complemento', max_length=60, null=True)),
                ('bairro', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Bairro', max_length=50)),
                ('imagem', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Imagem', max_length=200, null=True)),
                ('banner', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Banner', max_length=200, null=True)),
                ('logradouro', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Logradouro', max_length=60)),
            ],
            options={
                'db_table': 'Empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('idfabricante', models.AutoField(db_column='IDFabricante', primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Descricao', max_length=200, null=True)),
                ('coderp', models.IntegerField(blank=True, db_column='CodERP', null=True)),
            ],
            options={
                'db_table': 'Fabricante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FreteUf',
            fields=[
                ('idfreteuf', models.AutoField(db_column='IDFreteUF', primary_key=True, serialize=False)),
                ('uforigem', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='UFOrigem', max_length=2)),
                ('ufdestino', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='UFDestino', max_length=2)),
                ('vlminimo', models.DecimalField(db_column='VlMinimo', decimal_places=4, max_digits=19)),
                ('peracrescimo', models.DecimalField(blank=True, db_column='PerAcrescimo', decimal_places=2, max_digits=4, null=True)),
                ('perdesconto', models.DecimalField(blank=True, db_column='PerDesconto', decimal_places=2, max_digits=4, null=True)),
            ],
            options={
                'db_table': 'FreteUF',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LinhaEstrutura',
            fields=[
                ('idestrutura', models.AutoField(db_column='IDEstrutura', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'LinhaEstrutura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ListaCor',
            fields=[
                ('idlistacor', models.AutoField(db_column='IDListaCor', primary_key=True, serialize=False)),
                ('descricao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Descricao', max_length=25, unique=True)),
                ('cor', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Cor', max_length=20)),
            ],
            options={
                'db_table': 'ListaCor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('idmarca', models.AutoField(db_column='IDMarca', primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Descricao', max_length=200, null=True)),
                ('coderp', models.IntegerField(blank=True, db_column='CodERP', null=True)),
            ],
            options={
                'db_table': 'Marca',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MargemEstrutura',
            fields=[
                ('idmarestrutura', models.AutoField(db_column='IDMarEstrutura', primary_key=True, serialize=False)),
                ('perminimo', models.DecimalField(db_column='PerMinimo', decimal_places=2, max_digits=5)),
                ('permaximo', models.DecimalField(db_column='PerMaximo', decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'MargemEstrutura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('idoferta', models.AutoField(db_column='IDOferta', primary_key=True, serialize=False)),
                ('descricao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Descricao', max_length=200)),
                ('dtinicial', models.DateField(db_column='DtInicial')),
                ('dtfinal', models.DateField(db_column='DtFinal')),
            ],
            options={
                'db_table': 'Oferta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfertaEstrutura',
            fields=[
                ('idofertaestrutura', models.AutoField(db_column='IDOfertaEstrutura', primary_key=True, serialize=False)),
                ('desoferta', models.DecimalField(db_column='DesOferta', decimal_places=3, max_digits=7)),
                ('qtoferta', models.DecimalField(db_column='QtOferta', decimal_places=4, max_digits=19)),
                ('qtminima', models.DecimalField(db_column='QtMinima', decimal_places=4, max_digits=19)),
                ('qtmaxima', models.DecimalField(db_column='QtMaxima', decimal_places=4, max_digits=19)),
                ('desoferta2', models.DecimalField(blank=True, db_column='DesOferta2', decimal_places=3, max_digits=7, null=True)),
            ],
            options={
                'db_table': 'OfertaEstrutura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('idpagamento', models.AutoField(db_column='IDPagamento', primary_key=True, serialize=False)),
                ('prazodias', models.IntegerField(db_column='PrazoDias')),
                ('descpagamento', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DescPagamento', max_length=40)),
                ('qparcela', models.IntegerField(db_column='Qparcela')),
                ('coderp', models.IntegerField(db_column='CodERP')),
                ('situacao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Situacao', max_length=1)),
            ],
            options={
                'db_table': 'Pagamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PortalMensagem',
            fields=[
                ('idportalmensagem', models.AutoField(db_column='IDPortalMensagem', primary_key=True, serialize=False)),
                ('datainicial', models.DateTimeField(db_column='DataInicial')),
                ('datafinal', models.DateTimeField(db_column='DataFinal')),
                ('vendedor', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Vendedor', max_length=1)),
                ('varejo', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Varejo', max_length=1)),
                ('clienteb2b', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ClienteB2B', max_length=1)),
                ('clienteb2c', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ClienteB2C', max_length=1)),
                ('representante', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Representante', max_length=1)),
                ('mensagem', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Mensagem', max_length=250)),
            ],
            options={
                'db_table': 'PortalMensagem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrazoFaixa',
            fields=[
                ('prazodias', models.IntegerField(db_column='PrazoDias')),
                ('perdesconto', models.DecimalField(db_column='PerDesconto', decimal_places=2, max_digits=4)),
                ('peracrescimo', models.DecimalField(db_column='PerAcrescimo', decimal_places=2, max_digits=5)),
                ('vlminimo', models.DecimalField(db_column='VlMinimo', decimal_places=4, max_digits=19)),
                ('situacao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Situacao', max_length=1)),
                ('idprazofaixa', models.AutoField(db_column='IDPrazoFaixa', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'PrazoFaixa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrazoFinanceiro',
            fields=[
                ('idprazofinanceiro', models.AutoField(db_column='IDPrazoFinanceiro', primary_key=True, serialize=False)),
                ('descprazo', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DescPrazo', max_length=40)),
                ('datainicial', models.DateField(db_column='DataInicial')),
                ('datafinal', models.DateField(db_column='DataFinal')),
                ('situacao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Situacao', max_length=1)),
            ],
            options={
                'db_table': 'PrazoFinanceiro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Precocliente',
            fields=[
                ('idpreco', models.OneToOneField(db_column='IDPreco', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='backoffice.preco')),
                ('idcliente', models.IntegerField(db_column='IDCliente')),
            ],
            options={
                'db_table': 'PrecoCliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrecoFaixa',
            fields=[
                ('idprecofaixa', models.AutoField(db_column='IDPrecoFaixa', primary_key=True, serialize=False)),
                ('pervariacao', models.DecimalField(db_column='PerVariacao', decimal_places=4, max_digits=7)),
                ('tipovariacao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TipoVariacao', max_length=1)),
            ],
            options={
                'db_table': 'PrecoFaixa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrecoLocal',
            fields=[
                ('idpreco', models.OneToOneField(db_column='IDPreco', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='backoffice.preco')),
            ],
            options={
                'db_table': 'PrecoLocal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrecoPrazo',
            fields=[
                ('prazodias', models.IntegerField(db_column='PrazoDias')),
                ('idprecoprazo', models.AutoField(db_column='IDPrecoPrazo', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'PrecoPrazo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrecoProduto',
            fields=[
                ('idpreco', models.OneToOneField(db_column='IDPreco', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='backoffice.preco')),
                ('idproduto', models.IntegerField(db_column='IDProduto')),
                ('codembalagem', models.IntegerField(db_column='CodEmbalagem')),
                ('precobase', models.DecimalField(blank=True, db_column='PrecoBase', decimal_places=6, max_digits=19, null=True)),
                ('perdescmaximo', models.DecimalField(db_column='PerDescMaximo', decimal_places=3, max_digits=6)),
                ('situacao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Situacao', max_length=1)),
            ],
            options={
                'db_table': 'PrecoProduto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrecoUf',
            fields=[
                ('idpreco', models.OneToOneField(db_column='IDPreco', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='backoffice.preco')),
                ('ufvalida', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='UFValida', max_length=2)),
            ],
            options={
                'db_table': 'PrecoUF',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrecoUsuario',
            fields=[
                ('idpreco', models.OneToOneField(db_column='IDPreco', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='backoffice.preco')),
            ],
            options={
                'db_table': 'PrecoUsuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrecoVendedor',
            fields=[
                ('idpreco', models.OneToOneField(db_column='IDPreco', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='backoffice.preco')),
            ],
            options={
                'db_table': 'PrecoVendedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProdutoLocal',
            fields=[
                ('idproduto', models.IntegerField(db_column='IDProduto')),
                ('multvenda', models.DecimalField(blank=True, db_column='MultVenda', decimal_places=4, max_digits=19, null=True)),
                ('minvenda', models.DecimalField(blank=True, db_column='MinVenda', decimal_places=4, max_digits=19, null=True)),
                ('estoqueminimo', models.DecimalField(blank=True, db_column='EstoqueMinimo', decimal_places=4, max_digits=19, null=True)),
                ('estoquepadrao', models.DecimalField(blank=True, db_column='EstoquePadrao', decimal_places=4, max_digits=19, null=True)),
                ('permitirsaldonegativo', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='PermitirSaldoNegativo', max_length=1)),
                ('idprodutolocal', models.AutoField(db_column='IDProdutoLocal', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ProdutoLocal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProdutoMarca',
            fields=[
                ('idproduto', models.OneToOneField(db_column='IDProduto', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='backoffice.produto')),
                ('codfabricante', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='CodFabricante', max_length=50, null=True)),
                ('principal', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Principal', max_length=1)),
            ],
            options={
                'db_table': 'ProdutoMarca',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegiaoUf',
            fields=[
                ('idregiaouf', models.AutoField(db_column='IDRegiaoUF', primary_key=True, serialize=False)),
                ('uf', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='UF', max_length=2)),
                ('cidade', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Cidade', max_length=150, null=True)),
            ],
            options={
                'db_table': 'RegiaoUF',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegiaoVendedor',
            fields=[
                ('idregiao', models.OneToOneField(db_column='IDRegiao', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='backoffice.regiaovenda')),
                ('idusuario', models.IntegerField(db_column='IDUsuario')),
            ],
            options={
                'db_table': 'RegiaoVendedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TempCarteiraPedido',
            fields=[
                ('idoperacao', models.CharField(blank=True, db_column='IDOperacao', max_length=36, null=True)),
                ('idlocal', models.IntegerField(db_column='IDLocal')),
                ('fantasialocal', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='FantasiaLocal', max_length=40)),
                ('idvendedor', models.IntegerField(blank=True, db_column='IDVendedor', null=True)),
                ('nomevendedor', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='NomeVendedor', max_length=84, null=True)),
                ('idresponsavel', models.IntegerField(blank=True, db_column='IDResponsavel', null=True)),
                ('nomeresponsavel', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='NomeResponsavel', max_length=84, null=True)),
                ('idrepresentada', models.IntegerField(blank=True, db_column='IDRepresentada', null=True)),
                ('fantasiarepresentada', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='FantasiaRepresentada', max_length=73, null=True)),
                ('nrpedido', models.IntegerField(db_column='NrPedido')),
                ('idcliente', models.IntegerField(db_column='IDCliente')),
                ('fantasiacliente', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='FantasiaCliente', max_length=73, null=True)),
                ('dtpedido', models.DateField(db_column='DtPedido')),
                ('vlpedido', models.DecimalField(blank=True, db_column='VlPedido', decimal_places=4, max_digits=19, null=True)),
                ('nrseriedanfe', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='NrSerieDANFE', max_length=6, null=True)),
                ('nrdanfe', models.IntegerField(blank=True, db_column='NrDANFE', null=True)),
                ('dtemissao', models.DateTimeField(blank=True, db_column='DtEmissao', null=True)),
                ('vldanfe', models.DecimalField(blank=True, db_column='VlDANFE', decimal_places=4, max_digits=19, null=True)),
                ('situacaodanfe', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='SituacaoDANFE', max_length=4, null=True)),
                ('nrserietitulo', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='NrSerieTitulo', max_length=3, null=True)),
                ('nrtitulo', models.IntegerField(blank=True, db_column='NrTitulo', null=True)),
                ('qtparcela', models.SmallIntegerField(blank=True, db_column='QtParcela', null=True)),
                ('situacaopedido', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='SituacaoPedido', max_length=13)),
                ('idcarteirapedido', models.AutoField(db_column='IDCarteiraPedido', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'TempCarteiraPedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VolumeFaixa',
            fields=[
                ('idvolumefaixa', models.AutoField(db_column='IDVolumeFaixa', primary_key=True, serialize=False)),
                ('vlcomprasde', models.DecimalField(db_column='VlComprasDE', decimal_places=4, max_digits=19)),
                ('vlcomprasate', models.DecimalField(db_column='VlComprasATE', decimal_places=4, max_digits=19)),
                ('perdesconto', models.DecimalField(db_column='PerDesconto', decimal_places=2, max_digits=4)),
            ],
            options={
                'db_table': 'VolumeFaixa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkFlow',
            fields=[
                ('idworkflow', models.AutoField(db_column='IDWorkFlow', primary_key=True, serialize=False)),
                ('desworkflow', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DesWorkFlow', max_length=150)),
                ('situacao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Situacao', max_length=1)),
                ('coderp', models.IntegerField(blank=True, db_column='CodERP', null=True)),
            ],
            options={
                'db_table': 'WorkFlow',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='equipevenda',
            table='EquipeVenda',
        ),
        migrations.AlterModelTable(
            name='politicacomissao',
            table='PoliticaComissao',
        ),
        migrations.AlterModelTable(
            name='tipousuario',
            table='TipoUsuario',
        ),
        migrations.CreateModel(
            name='OfertaLocal',
            fields=[
                ('idoferta', models.OneToOneField(db_column='IDOferta', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='backoffice.oferta')),
            ],
            options={
                'db_table': 'OfertaLocal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PagamentoLocal',
            fields=[
                ('idpagamento', models.OneToOneField(db_column='IDPagamento', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='backoffice.pagamento')),
            ],
            options={
                'db_table': 'PagamentoLocal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PagamentoParcela',
            fields=[
                ('idpagamento', models.OneToOneField(db_column='IDPagamento', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='backoffice.pagamento')),
                ('nrparcela', models.IntegerField(db_column='NrParcela')),
                ('prparcela', models.DecimalField(db_column='PrParcela', decimal_places=3, max_digits=6)),
                ('qtdias', models.IntegerField(db_column='QtDias')),
            ],
            options={
                'db_table': 'PagamentoParcela',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PagamentoVendedor',
            fields=[
                ('idpagamento', models.OneToOneField(db_column='IDPagamento', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='backoffice.pagamento')),
            ],
            options={
                'db_table': 'PagamentoVendedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AcessoPerfilUsuario',
            fields=[
                ('idperfilusuario', models.AutoField(db_column='IDPerfilUsuario', primary_key=True, serialize=False)),
                ('idperfil', models.ForeignKey(blank=True, db_column='IDPerfil', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backoffice.acessoperfil')),
                ('idusuario', models.ForeignKey(blank=True, db_column='IDUsuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backoffice.usuario')),
            ],
            options={
                'db_table': 'AcessoPerfilUsuario',
            },
        ),
        migrations.CreateModel(
            name='AcessoPerfilMenu',
            fields=[
                ('idperfilmenu', models.AutoField(db_column='IDPerfilMenu', primary_key=True, serialize=False)),
                ('idmenu', models.ForeignKey(blank=True, db_column='IDMenu', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backoffice.menu')),
                ('idperfil', models.ForeignKey(blank=True, db_column='IDPerfil', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backoffice.acessoperfil')),
            ],
            options={
                'db_table': 'AcessoPerfilMenu',
            },
        ),
    ]
