# Generated by Django 4.2.6 on 2024-04-01 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0003_cascatafaixa_comfaixa_dashgrafico_dashgraficodados_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrigemVenda',
            fields=[
                ('idorigemvenda', models.AutoField(db_column='IDOrigemVenda', primary_key=True, serialize=False)),
                ('descricao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Descricao', max_length=30)),
                ('coderp', models.IntegerField(blank=True, db_column='CodERP', null=True)),
            ],
            options={
                'db_table': 'OrigemVenda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idpedido', models.BigAutoField(db_column='IDPedido', primary_key=True, serialize=False)),
                ('nrpedido', models.IntegerField(blank=True, db_column='NrPedido', null=True)),
                ('dtpedido', models.DateTimeField(blank=True, db_column='DtPedido', null=True)),
                ('codvendedor', models.IntegerField(db_column='CodVendedor')),
                ('codrepresentante', models.IntegerField(blank=True, db_column='CodRepresentante', null=True)),
                ('cnpjcpf', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='CNPJCPF', max_length=18)),
                ('contato', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Contato', max_length=60, null=True)),
                ('telcelular', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='TelCelular', max_length=15, null=True)),
                ('whats', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Whats', max_length=15, null=True)),
                ('email', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Email', max_length=100, null=True)),
                ('situacao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Situacao', max_length=2)),
                ('dtorcamento', models.DateTimeField(blank=True, db_column='DTOrcamento', null=True)),
                ('idcontato', models.IntegerField(blank=True, db_column='IDContato', null=True)),
                ('dtvalidade', models.DateField(blank=True, db_column='DtValidade', null=True)),
                ('idpedidoerp', models.BigIntegerField(blank=True, db_column='IDPedidoERP', null=True)),
                ('nroriginal', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='NrOriginal', max_length=60, null=True)),
            ],
            options={
                'db_table': 'Pedido',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='workflow',
            options={},
        ),
        migrations.CreateModel(
            name='Pedidowf',
            fields=[
                ('idpedido', models.OneToOneField(db_column='IDPedido', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='backoffice.pedido')),
                ('obsvendedor', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ObsVendedor', max_length=250, null=True)),
                ('obspedido', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ObsPedido', max_length=250, null=True)),
                ('obsnota', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ObsNota', max_length=250, null=True)),
            ],
            options={
                'db_table': 'PedidoWF',
                'managed': False,
            },
        ),
    ]
