# Generated by Django 4.2.6 on 2024-04-01 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0004_origemvenda_pedido_alter_workflow_options_pedidowf'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='ordem',
            field=models.IntegerField(blank=True, db_column='Ordem', null=True),
        ),
    ]
