# Generated by Django 4.2.6 on 2024-04-01 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0005_workflow_idlistacor_workflow_ordem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflow',
            options={'managed': False},
        ),
    ]
